# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sessionUi.ui'
#
# Created: Mon Sep 22 19:59:31 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtWidgets

class Ui_session_form(object):
    def setupUi(self, session_form):
        session_form.setObjectName("session_form")
        session_form.resize(452, 532)
        self.centralwidget = QtWidgets.QWidget(session_form)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sessionGB = QtWidgets.QGroupBox(self.centralwidget)
        self.sessionGB.setObjectName("sessionGB")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.sessionGB)
        self.horizontalLayout_6.setSpacing(2)
        self.horizontalLayout_6.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.sessionsCB = QtWidgets.QComboBox(self.sessionGB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sessionsCB.sizePolicy().hasHeightForWidth())
        self.sessionsCB.setSizePolicy(sizePolicy)
        self.sessionsCB.setObjectName("sessionsCB")
        self.horizontalLayout_6.addWidget(self.sessionsCB)
        self.setSessionPB = QtWidgets.QPushButton(self.sessionGB)
        self.setSessionPB.setObjectName("setSessionPB")
        self.horizontalLayout_6.addWidget(self.setSessionPB)
        self.verticalLayout_2.addWidget(self.sessionGB)
        self.actionsGB = QtWidgets.QGroupBox(self.centralwidget)
        self.actionsGB.setObjectName("actionsGB")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.actionsGB)
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.actionsCB = QtWidgets.QComboBox(self.actionsGB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actionsCB.sizePolicy().hasHeightForWidth())
        self.actionsCB.setSizePolicy(sizePolicy)
        self.actionsCB.setObjectName("actionsCB")
        self.horizontalLayout_4.addWidget(self.actionsCB)
        self.addPB = QtWidgets.QPushButton(self.actionsGB)
        self.addPB.setObjectName("addPB")
        self.horizontalLayout_4.addWidget(self.addPB)
        self.verticalLayout_2.addWidget(self.actionsGB)
        self.currentSessionGB = QtWidgets.QGroupBox(self.centralwidget)
        self.currentSessionGB.setObjectName("currentSessionGB")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.currentSessionGB)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sessionSCR = QtWidgets.QScrollArea(self.currentSessionGB)
        self.sessionSCR.setWidgetResizable(True)
        self.sessionSCR.setObjectName("sessionSCR")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 422, 300))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setSpacing(1)
        self.verticalLayout_5.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.sessionSCR.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.sessionSCR)
        self.savePB = QtWidgets.QPushButton(self.currentSessionGB)
        self.savePB.setObjectName("savePB")
        self.verticalLayout.addWidget(self.savePB)
        self.verticalLayout_2.addWidget(self.currentSessionGB)
        self.runsGB = QtWidgets.QGroupBox(self.centralwidget)
        self.runsGB.setTitle("")
        self.runsGB.setObjectName("runsGB")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.runsGB)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.executePB = QtWidgets.QPushButton(self.runsGB)
        self.executePB.setObjectName("executePB")
        self.horizontalLayout.addWidget(self.executePB)
        self.setDefaultPB = QtWidgets.QPushButton(self.runsGB)
        self.setDefaultPB.setObjectName("setDefaultPB")
        self.horizontalLayout.addWidget(self.setDefaultPB)
        self.verticalLayout_2.addWidget(self.runsGB)
        session_form.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(session_form)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 452, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        session_form.setMenuBar(self.menuBar)
        self.actionSession_Path = QtWidgets.QAction(session_form)
        self.actionSession_Path.setObjectName("actionSession_Path")
        self.menuSettings.addAction(self.actionSession_Path)
        self.menuBar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(session_form)
        QtCore.QMetaObject.connectSlotsByName(session_form)

    def retranslateUi(self, session_form):
        session_form.setWindowTitle(QtWidgets.QApplication.translate("session_form", "SirEngineThe3rd Exporter v1.0", None))
        self.sessionGB.setTitle(QtWidgets.QApplication.translate("session_form", "Sessions", None ))
        self.setSessionPB.setText(QtWidgets.QApplication.translate("session_form", "SET", None))
        self.actionsGB.setTitle(QtWidgets.QApplication.translate("session_form", "Actions", None))
        self.addPB.setText(QtWidgets.QApplication.translate("session_form", "ADD", None))
        self.currentSessionGB.setTitle(QtWidgets.QApplication.translate("session_form", "Current session", None))
        self.savePB.setText(QtWidgets.QApplication.translate("session_form", "&Save session", None))
        self.executePB.setText(QtWidgets.QApplication.translate("session_form", "&excute", None))
        self.setDefaultPB.setText(QtWidgets.QApplication.translate("session_form", "&SetDefault", None))
        self.menuSettings.setTitle(QtWidgets.QApplication.translate("session_form", "Settings", None))
        self.actionSession_Path.setText(QtWidgets.QApplication.translate("session_form", "Set session &Path", None))

