# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sessionUi.ui',
# licensing of 'sessionUi.ui' applies.
#
# Created: Thu Oct 10 10:57:13 2019
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_session_form(object):
    def setupUi(self, session_form):
        session_form.setObjectName("session_form")
        session_form.resize(452, 532)
        self.centralwidget = QtWidgets.QWidget(session_form)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.basePathGB = QtWidgets.QGroupBox(self.centralwidget)
        self.basePathGB.setObjectName("basePathGB")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.basePathGB)
        self.horizontalLayout_6.setSpacing(2)
        self.horizontalLayout_6.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_2.addWidget(self.basePathGB)
        self.actionsGB = QtWidgets.QGroupBox(self.centralwidget)
        self.actionsGB.setObjectName("actionsGB")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.actionsGB)
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.actionsCB = QtWidgets.QComboBox(self.actionsGB)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actionsCB.sizePolicy().hasHeightForWidth())
        self.actionsCB.setSizePolicy(sizePolicy)
        self.actionsCB.setObjectName("actionsCB")
        self.horizontalLayout_4.addWidget(self.actionsCB)
        self.addPB = QtWidgets.QPushButton(self.actionsGB)
        self.addPB.setObjectName("addPB")
        self.horizontalLayout_4.addWidget(self.addPB)
        self.verticalLayout_2.addWidget(self.actionsGB)
        self.currentSessionGB = QtWidgets.QGroupBox(self.centralwidget)
        self.currentSessionGB.setObjectName("currentSessionGB")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.currentSessionGB)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sessionSCR = QtWidgets.QScrollArea(self.currentSessionGB)
        self.sessionSCR.setWidgetResizable(True)
        self.sessionSCR.setObjectName("sessionSCR")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 422, 323))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.sessionSCR.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.sessionSCR)
        self.savePB = QtWidgets.QPushButton(self.currentSessionGB)
        self.savePB.setObjectName("savePB")
        self.verticalLayout.addWidget(self.savePB)
        self.verticalLayout_2.addWidget(self.currentSessionGB)
        self.runsGB = QtWidgets.QGroupBox(self.centralwidget)
        self.runsGB.setTitle("")
        self.runsGB.setObjectName("runsGB")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.runsGB)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.executePB = QtWidgets.QPushButton(self.runsGB)
        self.executePB.setObjectName("executePB")
        self.horizontalLayout.addWidget(self.executePB)
        self.setDefaultPB = QtWidgets.QPushButton(self.runsGB)
        self.setDefaultPB.setObjectName("setDefaultPB")
        self.horizontalLayout.addWidget(self.setDefaultPB)
        self.verticalLayout_2.addWidget(self.runsGB)
        session_form.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(session_form)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 452, 21))
        self.menuBar.setObjectName("menuBar")
        session_form.setMenuBar(self.menuBar)
        self.actionSession_Path = QtWidgets.QAction(session_form)
        self.actionSession_Path.setObjectName("actionSession_Path")

        self.retranslateUi(session_form)
        QtCore.QMetaObject.connectSlotsByName(session_form)

    def retranslateUi(self, session_form):
        session_form.setWindowTitle(QtWidgets.QApplication.translate("session_form", "Sir Engine the 3rd game exporter v1.0", None, -1))
        self.basePathGB.setTitle(QtWidgets.QApplication.translate("session_form", "Base path:", None, -1))
        self.actionsGB.setTitle(QtWidgets.QApplication.translate("session_form", "Actions", None, -1))
        self.addPB.setText(QtWidgets.QApplication.translate("session_form", "ADD", None, -1))
        self.currentSessionGB.setTitle(QtWidgets.QApplication.translate("session_form", "Current session", None, -1))
        self.savePB.setText(QtWidgets.QApplication.translate("session_form", "&Save session", None, -1))
        self.executePB.setText(QtWidgets.QApplication.translate("session_form", "&excute", None, -1))
        self.setDefaultPB.setText(QtWidgets.QApplication.translate("session_form", "&SetDefault", None, -1))
        self.actionSession_Path.setText(QtWidgets.QApplication.translate("session_form", "Set session &Path", None, -1))

