#pragma once
//in case you are wondering what this is, this is an X macro: https://en.wikipedia.org/wiki/X_Macro
//we are in need to translate our json PSO which contains back buffer formats from strings
//to actual type, using the Xmacro I was able to copy the header where is actually define
//and replace we chars for every line. Now we can for example automatically define a static
//unordered map to do the conversion, check PSOManager.cpp for seeing it in use
#define LIST_OF_FORMATS                                                        \
  X(DXGI_FORMAT_UNKNOWN)                                                       \
  X(DXGI_FORMAT_R32G32B32A32_TYPELESS)                                         \
  X(DXGI_FORMAT_R32G32B32A32_FLOAT)                                            \
  X(DXGI_FORMAT_R32G32B32A32_UINT)                                             \
  X(DXGI_FORMAT_R32G32B32A32_SINT)                                             \
  X(DXGI_FORMAT_R32G32B32_TYPELESS)                                            \
  X(DXGI_FORMAT_R32G32B32_FLOAT)                                               \
  X(DXGI_FORMAT_R32G32B32_UINT)                                                \
  X(DXGI_FORMAT_R32G32B32_SINT)                                                \
  X(DXGI_FORMAT_R16G16B16A16_TYPELESS)                                         \
  X(DXGI_FORMAT_R16G16B16A16_FLOAT)                                            \
  X(DXGI_FORMAT_R16G16B16A16_UNORM)                                            \
  X(DXGI_FORMAT_R16G16B16A16_UINT)                                             \
  X(DXGI_FORMAT_R16G16B16A16_SNORM)                                            \
  X(DXGI_FORMAT_R16G16B16A16_SINT)                                             \
  X(DXGI_FORMAT_R32G32_TYPELESS)                                               \
  X(DXGI_FORMAT_R32G32_FLOAT)                                                  \
  X(DXGI_FORMAT_R32G32_UINT)                                                   \
  X(DXGI_FORMAT_R32G32_SINT)                                                   \
  X(DXGI_FORMAT_R32G8X24_TYPELESS)                                             \
  X(DXGI_FORMAT_D32_FLOAT_S8X24_UINT)                                          \
  X(DXGI_FORMAT_R32_FLOAT_X8X24_TYPELESS)                                      \
  X(DXGI_FORMAT_X32_TYPELESS_G8X24_UINT)                                       \
  X(DXGI_FORMAT_R10G10B10A2_TYPELESS)                                          \
  X(DXGI_FORMAT_R10G10B10A2_UNORM)                                             \
  X(DXGI_FORMAT_R10G10B10A2_UINT)                                              \
  X(DXGI_FORMAT_R11G11B10_FLOAT)                                               \
  X(DXGI_FORMAT_R8G8B8A8_TYPELESS)                                             \
  X(DXGI_FORMAT_R8G8B8A8_UNORM)                                                \
  X(DXGI_FORMAT_R8G8B8A8_UNORM_SRGB)                                           \
  X(DXGI_FORMAT_R8G8B8A8_UINT)                                                 \
  X(DXGI_FORMAT_R8G8B8A8_SNORM)                                                \
  X(DXGI_FORMAT_R8G8B8A8_SINT)                                                 \
  X(DXGI_FORMAT_R16G16_TYPELESS)                                               \
  X(DXGI_FORMAT_R16G16_FLOAT)                                                  \
  X(DXGI_FORMAT_R16G16_UNORM)                                                  \
  X(DXGI_FORMAT_R16G16_UINT)                                                   \
  X(DXGI_FORMAT_R16G16_SNORM)                                                  \
  X(DXGI_FORMAT_R16G16_SINT)                                                   \
  X(DXGI_FORMAT_R32_TYPELESS)                                                  \
  X(DXGI_FORMAT_D32_FLOAT)                                                     \
  X(DXGI_FORMAT_R32_FLOAT)                                                     \
  X(DXGI_FORMAT_R32_UINT)                                                      \
  X(DXGI_FORMAT_R32_SINT)                                                      \
  X(DXGI_FORMAT_R24G8_TYPELESS)                                                \
  X(DXGI_FORMAT_D24_UNORM_S8_UINT)                                             \
  X(DXGI_FORMAT_R24_UNORM_X8_TYPELESS)                                         \
  X(DXGI_FORMAT_X24_TYPELESS_G8_UINT)                                          \
  X(DXGI_FORMAT_R8G8_TYPELESS)                                                 \
  X(DXGI_FORMAT_R8G8_UNORM)                                                    \
  X(DXGI_FORMAT_R8G8_UINT)                                                     \
  X(DXGI_FORMAT_R8G8_SNORM)                                                    \
  X(DXGI_FORMAT_R8G8_SINT)                                                     \
  X(DXGI_FORMAT_R16_TYPELESS)                                                  \
  X(DXGI_FORMAT_R16_FLOAT)                                                     \
  X(DXGI_FORMAT_D16_UNORM)                                                     \
  X(DXGI_FORMAT_R16_UNORM)                                                     \
  X(DXGI_FORMAT_R16_UINT)                                                      \
  X(DXGI_FORMAT_R16_SNORM)                                                     \
  X(DXGI_FORMAT_R16_SINT)                                                      \
  X(DXGI_FORMAT_R8_TYPELESS)                                                   \
  X(DXGI_FORMAT_R8_UNORM)                                                      \
  X(DXGI_FORMAT_R8_UINT)                                                       \
  X(DXGI_FORMAT_R8_SNORM)                                                      \
  X(DXGI_FORMAT_R8_SINT)                                                       \
  X(DXGI_FORMAT_A8_UNORM)                                                      \
  X(DXGI_FORMAT_R1_UNORM)                                                      \
  X(DXGI_FORMAT_R9G9B9E5_SHAREDEXP)                                            \
  X(DXGI_FORMAT_R8G8_B8G8_UNORM)                                               \
  X(DXGI_FORMAT_G8R8_G8B8_UNORM)                                               \
  X(DXGI_FORMAT_BC1_TYPELESS)                                                  \
  X(DXGI_FORMAT_BC1_UNORM)                                                     \
  X(DXGI_FORMAT_BC1_UNORM_SRGB)                                                \
  X(DXGI_FORMAT_BC2_TYPELESS)                                                  \
  X(DXGI_FORMAT_BC2_UNORM)                                                     \
  X(DXGI_FORMAT_BC2_UNORM_SRGB)                                                \
  X(DXGI_FORMAT_BC3_TYPELESS)                                                  \
  X(DXGI_FORMAT_BC3_UNORM)                                                     \
  X(DXGI_FORMAT_BC3_UNORM_SRGB)                                                \
  X(DXGI_FORMAT_BC4_TYPELESS)                                                  \
  X(DXGI_FORMAT_BC4_UNORM)                                                     \
  X(DXGI_FORMAT_BC4_SNORM)                                                     \
  X(DXGI_FORMAT_BC5_TYPELESS)                                                  \
  X(DXGI_FORMAT_BC5_UNORM)                                                     \
  X(DXGI_FORMAT_BC5_SNORM)                                                     \
  X(DXGI_FORMAT_B5G6R5_UNORM)                                                  \
  X(DXGI_FORMAT_B5G5R5A1_UNORM)                                                \
  X(DXGI_FORMAT_B8G8R8A8_UNORM)                                                \
  X(DXGI_FORMAT_B8G8R8X8_UNORM)                                                \
  X(DXGI_FORMAT_R10G10B10_XR_BIAS_A2_UNORM)                                    \
  X(DXGI_FORMAT_B8G8R8A8_TYPELESS)                                             \
  X(DXGI_FORMAT_B8G8R8A8_UNORM_SRGB)                                           \
  X(DXGI_FORMAT_B8G8R8X8_TYPELESS)                                             \
  X(DXGI_FORMAT_B8G8R8X8_UNORM_SRGB)                                           \
  X(DXGI_FORMAT_BC6H_TYPELESS)                                                 \
  X(DXGI_FORMAT_BC6H_UF16)                                                     \
  X(DXGI_FORMAT_BC6H_SF16)                                                     \
  X(DXGI_FORMAT_BC7_TYPELESS)                                                  \
  X(DXGI_FORMAT_BC7_UNORM)                                                     \
  X(DXGI_FORMAT_BC7_UNORM_SRGB)                                                \
  X(DXGI_FORMAT_AYUV)                                                          \
  X(DXGI_FORMAT_Y410)                                                          \
  X(DXGI_FORMAT_Y416)                                                          \
  X(DXGI_FORMAT_NV12)                                                          \
  X(DXGI_FORMAT_P010)                                                          \
  X(DXGI_FORMAT_P016)                                                          \
  X(DXGI_FORMAT_420_OPAQUE)                                                    \
  X(DXGI_FORMAT_YUY2)                                                          \
  X(DXGI_FORMAT_Y210)                                                          \
  X(DXGI_FORMAT_Y216)                                                          \
  X(DXGI_FORMAT_NV11)                                                          \
  X(DXGI_FORMAT_AI44)                                                          \
  X(DXGI_FORMAT_IA44)                                                          \
  X(DXGI_FORMAT_P8)                                                            \
  X(DXGI_FORMAT_A8P8)                                                          \
  X(DXGI_FORMAT_B4G4R4A4_UNORM)                                                \
  X(DXGI_FORMAT_P208) X(DXGI_FORMAT_V208) X(DXGI_FORMAT_V408)
