name: build
#triggered on push
on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build dependencies    
      run: |
        cd vendors 
        mkdir build
        cd build
        cmake ../ 
        cmake --build . --config ${{matrix.configuration}} 
    - name: Setup deps
      shell: powershell
      run: |
        ./ciSetup.ps1
    - name: Build engine
      env:	
        VULKAN_SDK: C:\VulkanSDK\1.2.141.0
      run: |
        mkdir build
        cd build
        cmake ../ -DBUILD_VULKAN=ON
        cmake --build . --config ${{matrix.configuration}} 
    - name: set enviroment
      run: echo 'C:\VulkanSDK\1.2.141.0\Bin' >> $GITHUB_PATH
    - name: copy dxc
      shell : cmd
      run : | 
        copy C:\VulkanSDK\1.2.141.0\Bin\dxcompiler.dll build\bin\${{matrix.configuration}}
    - name: Run tests
      env:	
        VULKAN_SDK: C:\VulkanSDK\1.2.141.0
      shell: cmd
      run: |
        cd build/bin/${{matrix.configuration}}
        dir
        dir ..\testData
        .\Tests.exe
