name: build
#triggered on push
on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build dependencies    
      run: |
        cd vendors 
        mkdir build
        cd build
        cmake ../ 
        cmake --build . --config ${{matrix.configuration}} 
    - name: install vk
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install vulkan-sdk  -y
    - name: Build engine
      run: |
        mkdir build
        cd build
        cmake ../ -DBUILD_VULKAN=ON
        cmake --build . --config ${{matrix.configuration}} 
    - name: Run tests
      shell: cmd
      run: |
        cd build/bin/${{matrix.configuration}}
        dir
        dir ..\testData
        .\Tests.exe
