name: Engine pipeline 2
#triggered on push
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Prepare
    - run:  cd vendors && mkdir build && cd build && cmake ../ && cmake --build .
