name: Engine pipeline
#triggered on push
on: [push]

jobs:
  build:
    name: build dependencies
    runs-on: windows-latest
    steps:
    - name: Prepare
      run: cd vendors && mkdir build && cd build && cmake ../ && cmake --build . 
